### ISSUE TITLE
urlgrabber not installable via pip

### ISSUE THREAD

**Issue by toabctl** [rpm-software-management/urlgrabber#4]
$ source blub/bin/activate
(blub) tom@basilikum:~/devel/urlgrabber$ pip install urlgrabber
Collecting urlgrabber
  Downloading urlgrabber-3.10.2.tar.gz (84kB)
    100% |████████████████████████████████| 92kB 385kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iwq_5fze/urlgrabber/setup.py", line 17, in <module>
        import urlgrabber as _urlgrabber
      File "/tmp/pip-build-iwq_5fze/urlgrabber/urlgrabber/__init__.py", line 55, in <module>
        from grabber import urlgrab, urlopen, urlread
    ImportError: No module named 'grabber'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iwq_5fze/urlgrabber/

**Comment by rustydb** [comment]
This is not using an absolute import, it should be `from urlgrabber.grabber import ...`. This is allowed in Py2, not Py3.

**Comment by techSash** [comment]
How can I install urlgrabber for python 3?

**Comment by keszybz** [comment]
This should be also fixed now.

**Comment by Conan-Kudo** [comment]
We haven't yet uploaded urlgrabber 4.0.0 to PyPI (mainly because I don't have the rights to do so yet), but that will hopefully be resolved in the coming days.

**Comment by toabctl** [comment]
> We haven't yet uploaded urlgrabber 4.0.0 to PyPI (mainly because I don't have the rights to do so yet), but that will hopefully be resolved in the coming days.

I uploaded a new version. Let me know if there are any problems

**Comment by mmalta-daily** [comment]
There is an issue while installing the new version:

`ImportError: No module named six`

**Comment by Conan-Kudo** [comment]
That's odd... I added `six` as a `setup_requires` to avoid that: https://github.com/rpm-software-management/urlgrabber/commit/be273c4b8d97960efcb4d53ec0d09286d3e942c3

**Comment by mmalta-daily** [comment]
If i installed manually six, it's working

**Comment by toabctl** [comment]
I think the solution would be, to not import the whole urlgrabber in setup.py but instead only the constants that are really needed.

**Comment by Conan-Kudo** [comment]
@toabctl That's what I thought it would be... I'll rework the setup.py and issue a new release.

**Comment by Conan-Kudo** [comment]
Fixed with ac524526d62980400713ba7dcfd78798feb9e829, will be part of the next release.

**Comment by Conan-Kudo** [comment]
@dmnks Can you please take care to release urlgrabber 4.1.0 to PyPI?

**Comment by toabctl** [comment]
@Conan-Kudo I can upload it.

**Comment by dmnks** [comment]
@toabctl Thanks!

**Comment by Conan-Kudo** [comment]
This is now fixed with `urlgrabber-4.1.0`.
