### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by brejoc** [rpm-software-management/urlgrabber#7]
I know that there where no plans to port urlgrabber to Python3, but at SUSE we've decided to stick to urlgrabber for various pieces of software and therefore started a Python3 port. Of course we'd like to upstream that. That's why I'm asking: Is there any chance to get this merged here?

**Comment by Conan-Kudo** [comment]
I would think so. The main issue historically has been testing to make sure the behavior remains sane with Python 3.

**Comment by brejoc** [comment]
Of course some additional testing would be needed, but currently all but two tests are passing.

**Comment by keszybz** [comment]
I guess this can be closed now.

**Comment by Conan-Kudo** [comment]
Resolved with the merge of #9 and release of urlgrabber-4.0.0.
